inherit_from: .rubocop_todo.yml
require:
    - rubocop-rails
AllCops:
    NewCops: enable
    Exclude:
        - 'config/environments/development.rb'
        - 'db/schema.rb'
        - 'bin/bundle'
        - 'app/models/application_record.rb'
